version: "3.9"

services:
  db:
    image: mariadb:10.4
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

  wordpress:
    depends_on:
      - db
    image: wordpress:5.7.2-php7.4-apache
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
      WORDPRESS_AUTH_KEY: "${WORDPRESS_AUTH_KEY}"
      WORDPRESS_SECURE_AUTH_KEY: "${WORDPRESS_SECURE_AUTH_KEY}"
      WORDPRESS_LOGGED_IN_KEY: "${WORDPRESS_LOGGED_IN_KEY}"
      WORDPRESS_NONCE_KEY: "${WORDPRESS_NONCE_KEY}"
      WORDPRESS_AUTH_SALT: "${WORDPRESS_AUTH_SALT}"
      WORDPRESS_SECURE_AUTH_SALT: "${WORDPRESS_SECURE_AUTH_SALT}"
      WORDPRESS_LOGGED_IN_SALT: "${WORDPRESS_LOGGED_IN_SALT}"
      WORDPRESS_NONCE_SALT: "${WORDPRESS_NONCE_SALT}"
      WORDPRESS_DEBUG: "${WORDPRESS_DEBUG}"
      WORDPRESS_CONFIG_EXTRA:
volumes:
  db_data: {}
  wordpress_data: {}
